# Generated by Django 4.0.2 on 2022-02-17 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='subjet',
            new_name='subject',
        ),
    ]
